### ISSUE TITLE
Feature: dephantomize comments

### ISSUE THREAD

**Issue by a13** [blue0513/phantom-inline-comment#20]
Another way to make phantoms persistent is to allow the user to convert phantom comments (all of them or only the active one) to the real ones. 

Phantomization would be a nice addition too

**Comment by blue0513** [comment]
Thx, good idea to dephantomize comments & phantomize comments!  

But I thought some users don't want to dephantomize the comments.  
So even though we should have such a __dephantomize_function__, we need other ways to persist comments.

**Comment by blue0513** [comment]
PR #16 was merged and we can persistent comments! So I thought _dephantomization_ does not critically be needed 👀  
I close this issue but if someone needs _dephatomization_ for other reasons, plz re-open this issue 🤝
